### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by majorovms** [juvirez/yandex-music-app#27]
```
Uncaught Exception:
TypeError: Cannot read property 'replace' of undefined
    at trackToMetaData (/Applications/Yandex Music (Unofficial).app/Contents/Resources/app.asar/src/main/features/mediaService.js:69:46)
    at IpcMain.<anonymous> (/Applications/Yandex Music (Unofficial).app/Contents/Resources/app.asar/src/main/features/mediaService.js:13:27)
    at IpcMain.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3850:15)
    at WebContents.emit (events.js:203:13)
```

![image](https://user-images.githubusercontent.com/49290534/83389501-61be3780-a401-11ea-8c54-55ae9eb6c617.png)

Просто вылетела ошибка. Но не упало, как играло так и играет.

**Comment by marselmustafin** [comment]
+
