### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by fatalist** [juvirez/yandex-music-app#46]
При открытии приложения попап с JS error:
Uncaught Exception:
Error: A number was expected
```
    at MediaService.setMetaData (/Applications/Yandex Music (Unofficial).app/Contents/Resources/app.asar/node_modules/electron-media-service/src/darwin/index.js:49:18)
    at IpcMain.<anonymous> (/Applications/Yandex Music (Unofficial).app/Contents/Resources/app.asar/src/main/features/mediaService.js:23:16)
    at IpcMain.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3850:15)
    at WebContents.emit (events.js:203:13)
```
<img width="1298" alt="изображение" src="https://user-images.githubusercontent.com/313991/94986053-2759d800-0564-11eb-9ca1-223d7b0f6a5b.png">

**Comment by juvirez** [comment]
Это уже пофикшено в #29
Попробуй релиз [v1.6.0-alpha.1](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0-alpha.1)
