### ISSUE TITLE
Алерт при попытке свернуть приложение (кнопка х)

### ISSUE THREAD

**Issue by amirgali** [juvirez/yandex-music-app#91]
Скрин: https://yadi.sk/i/MjFtLXTUA4v_eA
MacBook Air (M1, 2020)

Uncaught Exception:
SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at Request._callback (/Applications/Yandex Music (Unofficial).app/Contents/Resources/app.asar/node_modules/electron-google-analytics/lib/index.js:593:29)
at Request.self.callback (/Applications/Yandex Music (Unofficial).app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
at Request.emit (events.js:203:13)
at Request.<anonymous> (/Applications/Yandex Music (Unofficial).app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
at Request.emit (events.js:203:13)
at IncomingMessage.<anonymous> (/Applications/Yandex Music (Unofficial).app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:291:20)
at IncomingMessage.emit (events.js:208:15)
at endReadableNT (_stream_readable.js:1168:12)

**Comment by juvirez** [comment]
[released](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0)
